version: '3.1'

services:
  db:
    image: mysql:8-oracle
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce-test
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  express-sequelize:
    build: ./16-express-sequelize
    ports:
      - 3000:3000
